// ---------------------------------------------------------------------------
// Voorbeelddata voor de Marktplaats Scraper demo.
//
// LET OP: dit zijn OPGENOMEN voorbeeld-aanbiedingen, geen live data. De echte
// scraper (Python + Flask backend in deze repo) haalt deze velden van
// Marktplaats: title, price, location, date, link, image_url, description.
// Hier gebruiken we category-gebaseerde thumbnails zodat de demo 100% offline
// in de browser werkt, zonder externe requests of CORS-problemen.
// ---------------------------------------------------------------------------

const SAMPLE_LISTINGS = [
  {
    id: "m2001",
    title: "iPhone 14 Pro 256GB Deep Purple",
    price: 749,
    priceText: "€ 749,00",
    location: "Amsterdam",
    distanceKm: 4,
    date: "Vandaag",
    dateOrder: 0,
    condition: "Zo goed als nieuw",
    category: "telefoon",
    description: "iPhone 14 Pro, 256GB, accu 94%. Compleet met doos en oplader. Geen krasjes.",
  },
  {
    id: "m2002",
    title: "PlayStation 5 Slim Disc + 2 controllers",
    price: 420,
    priceText: "€ 420,00",
    location: "Utrecht",
    distanceKm: 38,
    date: "Vandaag",
    dateOrder: 0,
    condition: "Gebruikt",
    category: "console",
    description: "PS5 Slim met disc drive, twee DualSense controllers en 3 games.",
  },
  {
    id: "m2003",
    title: "Nintendo Switch OLED Wit",
    price: 245,
    priceText: "€ 245,00",
    location: "Rotterdam",
    distanceKm: 57,
    date: "Gisteren",
    dateOrder: 1,
    condition: "Zo goed als nieuw",
    category: "console",
    description: "Switch OLED model, nauwelijks gebruikt. Inclusief beschermhoes.",
  },
  {
    id: "m2004",
    title: "MacBook Air M2 13\" 8/256GB",
    price: 879,
    priceText: "€ 879,00",
    location: "Den Haag",
    distanceKm: 52,
    date: "Vandaag",
    dateOrder: 0,
    condition: "Gebruikt",
    category: "laptop",
    description: "MacBook Air M2, midnight. 112 laadcycli. Lichte gebruikssporen onderkant.",
  },
  {
    id: "m2005",
    title: "Samsung Galaxy S23 128GB",
    price: 389,
    priceText: "€ 389,00",
    location: "Eindhoven",
    distanceKm: 110,
    date: "2 dagen geleden",
    dateOrder: 2,
    condition: "Gebruikt",
    category: "telefoon",
    description: "Galaxy S23 Phantom Black. Werkt perfect, screenprotector zit erop.",
  },
  {
    id: "m2006",
    title: "Trek Marlin 7 mountainbike maat L",
    price: 540,
    priceText: "€ 540,00",
    location: "Groningen",
    distanceKm: 178,
    date: "Gisteren",
    dateOrder: 1,
    condition: "Gebruikt",
    category: "fiets",
    description: "Trek Marlin 7, 2022. Net onderhouden, nieuwe remblokken.",
  },
  {
    id: "m2007",
    title: "LEGO Star Wars Millennium Falcon 75257",
    price: 95,
    priceText: "€ 95,00",
    location: "Amsterdam",
    distanceKm: 6,
    date: "Vandaag",
    dateOrder: 0,
    condition: "Gebruikt",
    category: "speelgoed",
    description: "Compleet gebouwd met handleiding. Alle minifiguren aanwezig.",
  },
  {
    id: "m2008",
    title: "Sony WH-1000XM5 koptelefoon",
    price: 199,
    priceText: "€ 199,00",
    location: "Utrecht",
    distanceKm: 41,
    date: "3 dagen geleden",
    dateOrder: 3,
    condition: "Zo goed als nieuw",
    category: "audio",
    description: "Noise cancelling koptelefoon, zwart. Met originele case en kabel.",
  },
  {
    id: "m2009",
    title: "IKEA MALM bureau wit 140x65",
    price: 45,
    priceText: "€ 45,00",
    location: "Almere",
    distanceKm: 28,
    date: "Gisteren",
    dateOrder: 1,
    condition: "Gebruikt",
    category: "meubel",
    description: "Stevig bureau, kleine kras op het blad. Ophalen in Almere.",
  },
  {
    id: "m2010",
    title: "Canon EOS R10 body + 18-45mm",
    price: 825,
    priceText: "€ 825,00",
    location: "Tilburg",
    distanceKm: 100,
    date: "Vandaag",
    dateOrder: 0,
    condition: "Zo goed als nieuw",
    category: "camera",
    description: "Spiegelloze camera, 4.300 ontspanningen. Inclusief kitlens en tas.",
  },
  {
    id: "m2011",
    title: "Gratis verhuisdozen (set van 20)",
    price: 0,
    priceText: "Gratis",
    location: "Haarlem",
    distanceKm: 20,
    date: "Gisteren",
    dateOrder: 1,
    condition: "Gebruikt",
    category: "meubel",
    description: "20 stevige verhuisdozen, gratis op te halen. Zijn nog goed bruikbaar.",
  },
  {
    id: "m2012",
    title: "Vintage platenspeler Technics SL-1200",
    price: 0,
    priceText: "Bieden",
    location: "Nijmegen",
    distanceKm: 120,
    date: "4 dagen geleden",
    dateOrder: 4,
    condition: "Gebruikt",
    category: "audio",
    description: "Klassieke draaitafel. In nette staat, draait soepel. Prijs in overleg.",
    biddingOnly: true,
  },
];

// Aanbiedingen die de "monitor" later als nieuwe match kan binnenhalen.
// Deze zitten NIET in de begin-resultaten, ze 'verschijnen' via de toast,
// precies zoals de echte scraper periodiek nieuwe advertenties oppikt.
const INCOMING_MATCHES = [
  {
    id: "m3001",
    title: "iPhone 15 Pro 128GB Natural Titanium",
    price: 899,
    priceText: "€ 899,00",
    location: "Amsterdam",
    distanceKm: 3,
    date: "Zojuist",
    dateOrder: -1,
    condition: "Nieuw",
    category: "telefoon",
    description: "Net geopend, niet gebruikt. Inclusief bon en 2 jaar garantie.",
    isNew: true,
  },
  {
    id: "m3002",
    title: "PlayStation 5 Pro + extra controller",
    price: 699,
    priceText: "€ 699,00",
    location: "Amstelveen",
    distanceKm: 9,
    date: "Zojuist",
    dateOrder: -1,
    condition: "Zo goed als nieuw",
    category: "console",
    description: "PS5 Pro, 2 maanden oud. Compleet in doos met extra controller.",
    isNew: true,
  },
  {
    id: "m3003",
    title: "MacBook Pro 14\" M3 Pro 18/512GB",
    price: 1650,
    priceText: "€ 1.650,00",
    location: "Diemen",
    distanceKm: 7,
    date: "Zojuist",
    dateOrder: -1,
    condition: "Zo goed als nieuw",
    category: "laptop",
    description: "Space black, 23 laadcycli. Als nieuw, met originele doos.",
    isNew: true,
  },
];
